---
- name: Patch Red Hat Servers
  hosts: linux
  become: yes
  become_method: su
  become_user: root
  gather_facts: yes
  tasks:
    - name: Update yum packages
      yum:
        name: '*'
        state: latest
      when: ansible_os_family == "RedHat"
