---
- name: Patch Red Hat Servers
  hosts: linux
  become_method: sudo
  tasks:
    - name: Update yum packages
      yum:
        name: '*'
        state: latest
      when: ansible_os_family == "RedHat"
